version: "3.8"
services:
  db:
    image: mariadb:latest
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    hostname: "mariadb-pirogov.net"
    networks:
      - pirogov-network
    volumes:
      - ./backend/env/dumps/${MOST_RECENT}.sql:/docker-entrypoint-initdb.d/latest.sql
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD="yes"
      - MOST_RECENT

  pirogov-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    image: pirogov-backend
    container_name: pirogov-backend
    restart: always
    ports:
      - "8000:8000"
    networks:
     - pirogov-network

  pirogov-nginx:
    image: nginx:latest
    container_name: pirogov-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend/html:/srv/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - pirogov-network

networks:
  pirogov-network:
