version: "3.8"
services:
  db:
    image: mariadb:latest
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    hostname: "mariadb-pirogov.net"
    networks:
      - pirogov-network
    volumes:
      - ./backend/env/dumps/${MOST_RECENT}.sql:/docker-entrypoint-initdb.d/latest.sql
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD="yes"
      - MOST_RECENT

  pirogov-backend:
    build:
      context: ./backend
    depends_on:
      - db
    image: pirogov-backend
    hostname: "pirogov-backend.net"
    container_name: pirogov-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - dataset:/app/dataset
      - markup:/app/markup
    networks:
     - pirogov-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]

  pirogov-frontend:
    build:
      context: ./frontend
    depends_on:
      - pirogov-backend
    image: pirogov-frontend
    container_name: pirogov-frontend
    hostname: "pirogov-frontend.net"
    restart: always
    ports:
      - "3000:3000"
    networks:
     - pirogov-network

  pirogov-frontend:
    build:
      context: ./frontend
    depends_on:
      - pirogov-backend
    image: pirogov-frontend
    container_name: pirogov-frontend
    hostname: "pirogov-frontend.net"
    restart: always
    ports:
      - "3000:3000"
    networks:
     - pirogov-network

  pirogov-nginx:
    image: nginx:latest
    container_name: pirogov-nginx
    restart: always
    depends_on:
      - pirogov-frontend
      - pirogov-backend
    ports:
      - "80:80"
    volumes:
      - ./frontend/html:/srv/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - pirogov-network

networks:
  pirogov-network:

volumes:
  dataset:
  markup: