version: "3.8"
services:
  db:
    image: mariadb:latest
    container_name: db
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./dumps/${MOST_RECENT}.sql:/docker-entrypoint-initdb.d/latest.sql
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD="yes"
      - MOST_RECENT
    env_file:
      - .env
